<option value="fork">Vidlice</option>
<option value="f_axle">Přední osa</option>
<option value="stem">Představec</option>
<option value="bars">Řidítka</option>
<option value="grip">Gripy</option>
<option value="brakes">Brzdy (páky + třmeny)</option>
<option value="shifter">Přehazovačka</option>
<option value="f_shifter">Přední přehazovačka</option>
<option value="frame">Rám</option>
<option value="headset">Hlavové složení</option>
<option value="seattube">Sedlovka</option>
<option value="seat">Sedlo</option>
<option value="bb">Středové složení</option>
<option value="cranks">Kliky</option>
<option value="pedals">Pedály</option>
<option value="f_wheel">Přední kolo (ráfek + střed)</option>
<option value="r_wheel">Zadní kolo (ráfek + střed)</option>
<option value="f_tire">Přední plášť</option>
<option value="r_tire">Zadní plášť</option>
<option value="b_pads">Brzdové destičky</option>
<option value="f_disc">Přední kotouč</option>
<option value="r_disc">Zadní kotouč</option>
<option value="chain">Řetěz</option>
<option value="f_speed">Převodník</option>
<option value="acces">Příslušenství</option>